apiVersion: v1
kind: PersistentVolume
metadata:
  name: host-pv
spec: 
  capacity:
    storage: 500M
  volumeMode: Filesystem
  storageClassName: standard
  accessModes: 
    - ReadWriteOnce
  hostPath:
    path: /data/
    type: DirectoryOrCreate