---
- name: Provision EC2 Instance on AWS
  hosts: localhost
  connection: local
  gather_facts: false

  tasks:
    # First upload the key to AWS
    - name: Upload SSH key to AWS
      amazon.aws.ec2_key:
        name: ansibel_key
        key_material: "{{ lookup('file', '/home/ubuntu/keys/ansibel_key.pub') }}"
        region: us-east-1
      register: key_upload
      tags: key

    # Create security group
    - name: Create security group
      amazon.aws.ec2_security_group:
        name: ansible-sg
        description: "Security group for Ansible automation"
        region: us-east-1
        rules:
          - proto: tcp
            from_port: 22
            to_port: 22
            cidr_ip: 0.0.0.0/0
          - proto: tcp
            from_port: 80
            to_port: 80
            cidr_ip: 0.0.0.0/0
        tags:
          Name: ansible-sg
      register: sg_result
      tags: security

    # Launch instance using the uploaded key
    - name: Launch EC2 instance
      amazon.aws.ec2_instance:
        name: Automated-instance-terraform
        key_name: ansibel_key  # Only use the key name here
        instance_type: t2.micro
        image_id: ami-020cba7c55df1f615
        region: us-east-1
        security_group: ansible-sg
        wait: yes
        tags:
          Name: Automated-instance-terraform
          Environment: dev
      register: ec2_result
      tags: instance

    - name: Show result of EC2 provisioning
      debug:
        var: ec2_result
      tags: debug