replicaCount: 1

image:
  repository: shivachouhan/snake-ladder-game
  pullPolicy: IfNotPresent
  tag: mongo_app_02

mongo:
  image: mongo:4.4.18
  host: service-mongodb
  port: 27017

containerPort: 3000

service:
  type: ClusterIP
  port: 80

storage:
  size: 500Mi
  path: /data/

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}