apiVersion: v1
kind: PersistentVolume
metadata:
  name: host-pv
spec:
  capacity:
    storage: {{ .Values.persistentVolume.size }}
  volumeMode: Filesystem
  storageClassName: {{ .Values.persistentVolume.storageClass }}
  accessModes: 
    {{- range .Values.persistentVolume.accessModes }}
    - {{ . }}
    {{- end }}
  hostPath:
    path: {{ .Values.persistentVolume.path }}
    type: DirectoryOrCreate