apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-app
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: mongo-app
  template:
    metadata:
      labels:
        app: mongo-app
    spec:
      containers:
        - name: mongo-app
          image: {{ .Values.mongodb.image }}
          volumeMounts:
            - mountPath: /data/db
              name: mongo-vol
      volumes:
        - name: mongo-vol
          persistentVolumeClaim:
            claimName: host-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: service-mongodb
spec:
  selector:
    app: mongo-app
  ports:
    - name: tcp
      port: {{ .Values.mongodb.port }}
      targetPort: {{ .Values.mongodb.port }}
