datadog:
  clusterName: "minikube"
  apiKeyExistingSecret: "datadog-secret"
  site: "us5.datadoghq.com"

  # APM Configuration
  apm:
    instrumentation:
      enabled: true
      targets:
        - name: "default-target"
          ddTraceVersions:
            java: "1"
            python: "3"
            js: "5"
            php: "1"
            dotnet: "3"

  # Logs Configuration
  logs:
    enabled: true
    containerCollectAll: true

  # Kubelet Configuration - Enhanced for Minikube
  kubelet:
    tlsVerify: false  # Required for Minikube's self-signed certs
    host:
      valueFrom:
        fieldRef:
          fieldPath: status.hostIP
    hostCapabilities:
      - hostIP
      - hostname
    authTokenPath: "/var/run/secrets/kubernetes.io/serviceaccount/token"

  # Process Monitoring
  processAgent:
    enabled: true
    processCollection: true

  # Disable problematic io integration
  confd:
    io.yaml: |-
      init_config:
      instances: [{}]

  # Additional debug logging
  logLevel: "DEBUG"

# Cluster Agent Configuration
clusterAgent:
  enabled: true
  replicas: 2
  createPodDisruptionBudget: true
  admissionController:
    enabled: true
    mutateUnlabelled: false
  resources:
    requests:
      cpu: "200m"
      memory: "256Mi"
    limits:
      cpu: "500m"
      memory: "512Mi"

# Node Agent Configuration
agents:
  useHostNetwork: true
  useHostPID: true
  # Add tolerations for Minikube
  tolerations:
    - operator: Exists
  containers:
    agent:
      resources:
        requests:
          cpu: "100m"
          memory: "128Mi"
        limits:
          cpu: "300m"
          memory: "256Mi"
    processAgent:
      resources:
        requests:
          cpu: "100m"
          memory: "128Mi"
    traceAgent:
      resources:
        requests:
          cpu: "100m"
          memory: "128Mi"

# Optional: Kube-State-Metrics integration
kubeStateMetricsCore:
  enabled: true