{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "simple-webapp.fullname" . }}
  labels:
    {{- include "simple-webapp.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  rules:
  - host: {{ .Values.ingress.hosts[0].host }}
    http:
      paths:
      - path: {{ .Values.ingress.hosts[0].paths[0] }}
        pathType: Prefix
        backend:
          service:
            name: {{ include "simple-webapp.fullname" . }}
            port:
              number: {{ .Values.service.port }}
{{- end }}
