apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "helm-chart.serviceAccountName" . }}
  labels:
    app: {{ include "simple-webapp.name" . }}
{{- if .Values.serviceAccount.annotations }}
  annotations:
{{ toYaml .Values.serviceAccount.annotations | indent 4 }}
{{- end }}
