pipeline {
    agent any

    environment {
        SONAR_SCANNER_HOME = tool 'SonarQubeScanner-7.1.0.4889'  // Ensure this tool is configured
    }

    stages {
        stage('Setup Python Virtual Env') {
            steps {
                dir('python_sonar_jenkins_project') {
                    sh '''
                        python3 -m venv venv
                        source venv/bin/activate
                        pip install --upgrade pip
                        pip install pytest coverage
                    '''
                }
            }
        }

        stage('Run Tests and Generate Coverage') {
            steps {
                dir('python_sonar_jenkins_project') {
                    sh '''
                        source venv/bin/activate
                        coverage run -m pytest
                        coverage report
                        coverage xml
                    '''
                }
            }
        }

        stage('SonarQube Analysis') {
            steps {
                dir('python_sonar_jenkins_project') {
                    withSonarQubeEnv('Sonar_Local') {
                        sh '''
                            source venv/bin/activate
                            ${SONAR_SCANNER_HOME}/bin/sonar-scanner
                        '''
                    }
                }
            }
        }
    }
}