prometheus:
  prometheusSpec:
    additionalScrapeConfigsSecret:
      enabled: true
      name: additional-scrape-configs
      key: additional-scrape-configs.yaml
    # Add volume mount if not automatically created
    volumes:
      - name: additional-scrape-configs
        secret:
          secretName: additional-scrape-configs
    volumeMounts:
      - name: additional-scrape-configs
        mountPath: /etc/prometheus/scrape_configs
        readOnly: true

# grafana:
#   enabled: true
#   grafana.ini:
#     smtp:
#       enabled: true
#       host: "smtp.gmail.com:587"
#       user: "shivanandchouhan959@gmail.com"
#       password: "$__file{/etc/grafana-secrets/smtp-password}"
#       from_address: "shivanandchouhan959@gmail.com"
#       from_name: "Grafana Alerts"
  
#   env:
#     GF_SMTP_PASSWORD:
#       secretKeyRef:
#         name: grafana-smtp-password
#         key: smtp_password