apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-springboot-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-springboot-app
  template:
    metadata:
      labels:
        app: hello-springboot-app
    spec:
      containers:
      - name: hello-springboot-app
        image: 017373484103.dkr.ecr.us-east-1.amazonaws.com/hello-springboot-app:latest  # Full ECR path
        imagePullPolicy: Always  # Always pull the latest image
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: hello-springboot-app-service
spec:
  type: LoadBalancer
  selector:
    app: hello-springboot-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080