version: 0.2

env:
  variables:
    EKS_CLUSTER_NAME: "wonderful-rock-potato"
    AWS_REGION: "us-east-1"

  build:
    commands:
      - echo "Configuring kubectl access..."
      - aws eks update-kubeconfig --name $EKS_CLUSTER_NAME --region $AWS_REGION
      - echo "Getting service URL..."
      - SERVICE_URL=$(kubectl get svc hello-springboot-app-service -o jsonpath='{.status.loadBalancer.ingress[0].hostname}')
      - echo "Application URL:" 
      - echo "http://$SERVICE_URL"
      