version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      - apt-get update -y
      - apt-get install -y maven
      - curl -LO "https://dl.k8s.io/release/$(curl -Ls https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
      - chmod +x kubectl
      - mv kubectl /usr/local/bin/

  pre_build:
    commands:
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 017373484103.dkr.ecr.us-east-1.amazonaws.com

  build:
    commands:
      - echo "Building application"
      - cd Jenkins_Assignment_7/hello-springboot-app
      - mvn clean package -DskipTests || echo "Build failed"
      - docker build -t hello-springboot-app . || echo "Docker build failed"

  post_build:
    commands:
      - echo "Deploying to EKS"
      - docker tag hello-springboot-app:latest 017373484103.dkr.ecr.us-east-1.amazonaws.com/hello-springboot-app:latest || echo "Tagging failed"
      - docker push 017373484103.dkr.ecr.us-east-1.amazonaws.com/hello-springboot-app:latest || echo "Push failed"
      - aws eks update-kubeconfig --region us-east-1 --name wonderful-rock-potato
      - kubectl apply -f deployment.yaml || echo "K8s deployment failed"
      - kubectl get pods

artifacts:
  files:
    - Jenkins_Assignment_7/hello-springboot-app/target/*.jar