phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      - echo "Updating packages and installing Docker & Maven"
      - apt-get update
      - apt-get install -y maven docker.io

  pre_build:
    commands:
      - echo "Verifying Docker is working"
      - docker --version
      - echo "Logging into ECR"
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 017373484103.dkr.ecr.us-east-1.amazonaws.com

  build:
    commands:
      - echo "Building Maven project"
      - mvn clean package
      - echo "Building Docker image"
      - docker build -t hello-springboot-app .

  post_build:
    commands:
      - echo "Deploying to EKS"
      - curl -LO "https://dl.k8s.io/release/$(curl -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
      - chmod +x kubectl && mv kubectl /usr/local/bin/
      - aws eks update-kubeconfig --region us-east-1 --name wonderful-rock-potato
      - kubectl apply -f deployment.yaml
