version: 0.2

env:
  variables:
    REPOSITORY_NAME: "hello-springboot-app"
    AWS_REGION: "us-east-1"
    EKS_CLUSTER_NAME: "wonderful-rock-potato"
    MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      - echo "Installing required tools..."
      - apt-get update -y
      - apt-get install -y maven
      - curl -LO "https://dl.k8s.io/release/$(curl -Ls https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
      - chmod +x kubectl
      - mv kubectl /usr/local/bin/
      - echo "Verifying AWS permissions..."
      - aws sts get-caller-identity

  pre_build:
    commands:
      - echo "Setting up AWS credentials..."
      - export AWS_ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
      - echo "Account ID: $AWS_ACCOUNT_ID"
      - echo "Logging in to Amazon ECR..."
      - if ! aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com; then
          echo "Failed to login to ECR. Checking permissions...";
          aws iam get-user || aws iam get-role --role-name $CODEBUILD_SERVICE_ROLE;
          exit 1;
        fi
      - echo "Checking for ECR repository..."
      - if ! aws ecr describe-repositories --repository-names $REPOSITORY_NAME --region $AWS_REGION; then
          echo "Creating ECR repository...";
          aws ecr create-repository --repository-name $REPOSITORY_NAME --region $AWS_REGION \
            --image-scanning-configuration scanOnPush=true \
            --image-tag-mutability MUTABLE;
        fi

  build:
    commands:
      - echo "Building Java application..."
      - mvn clean package
      - echo "Building Docker image..."
      - docker build -t $REPOSITORY_NAME:latest .
      - docker tag $REPOSITORY_NAME:latest $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$REPOSITORY_NAME:latest

  post_build:
    commands:
      - echo "Pushing Docker image to ECR..."
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$REPOSITORY_NAME:latest
      - echo "Configuring kubectl..."
      - aws eks update-kubeconfig --name $EKS_CLUSTER_NAME --region $AWS_REGION
      - echo "Deploying to EKS..."
      - kubectl apply -f deployment.yaml
      - echo "Verifying deployment..."
      - kubectl rollout status deployment/hello-springboot-app --timeout=300s
      - echo "Service URL:"
      - kubectl get svc hello-springboot-app-service -o jsonpath='{.status.loadBalancer.ingress[0].hostname}'

cache:
  paths:
    - '.m2/**/*'
    - 'target/**/*'