apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-springboot-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-springboot-app
  template:
    metadata:
      labels:
        app: hello-springboot-app
    spec:
      containers:
      - name: hello-springboot-app
        image: hello-springboot-app:latest
        ports:
        - containerPort: 8080
---

apiVersion: v1
kind: Service
metadata:
  name: hello-springboot-app-service
spec:
  type: NodePort
  selector:
    app: hello-springboot-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30500
