// Jenkinsfile for hello-springboot-app
pipeline {
    agent java-node
    environment {
        DOCKERHUB_CREDENTIALS = credentials('valaxy-dockerhub')
    }
    stages {
        stage('SCM Checkout') {
            steps {
                git 'https://github.com/ShivaChouhan/devops_training.git'
            }
        }
        stage('Build JAR') {
            steps {
                dir('Jenkins_Assignment_7/hello-springboot-app') {
                    sh 'mvn clean package'
                }
            }
        }
        stage('Build Docker Image') {
            steps {
                dir('Jenkins_Assignment_7/hello-springboot-app') {
                    sh 'docker build -t shivachouhan/snake-ladder-game:hello-springboot-app_$BUILD_NUMBER .'
                }
            }
        }
        stage('Login to DockerHub') {
            steps {
                sh 'echo $DOCKERHUB_CREDENTIALS_PSW | docker login -u $DOCKERHUB_CREDENTIALS_USR --password-stdin'
            }
        }
        stage('Push Image') {
            steps {
                dir('Jenkins_Assignment_7/hello-springboot-app') {
                    sh 'docker push shivachouhan/snake-ladder-game:hello-springboot-app_$BUILD_NUMBER'
                }
            }
        }
    }
    post {
        always {
            sh 'docker logout'
        }
    }
}