name: Java Docker K8s Deployment

on:
  push:
    branches:
      - main  # Trigger only when code is pushed to 'main' branch
    paths:
      - 'Jenkins_Assignment_7/hello-springboot-app/**'  # Only trigger when files in this path change

jobs:
  build-and-deploy:
    runs-on: [self-hosted, shivanad-chouhan-VirtualBox]  # Use a self-hosted runner with the specified label

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Verify Minikube Status
        run: minikube status

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build JAR with Maven
        working-directory: Jenkins_Assignment_7/hello-springboot-app
        run: mvn clean package

      - name: Configure Docker to Use Minikube
        run: eval $(minikube docker-env)

      - name: Build Docker Image
        working-directory: Jenkins_Assignment_7/hello-springboot-app
        run: |
          eval $(minikube docker-env)
          docker build -t hello-springboot-app:latest .

      - name: Verify Docker Image
        run: |
          eval $(minikube docker-env)
          docker images | grep hello-springboot-app || echo "Image not found!"
      
      - name: Delete and Recreate Deployment
        working-directory: Jenkins_Assignment_7/hello-springboot-app
        run: |
          eval $(minikube docker-env)
          kubectl delete deployment hello-springboot-app || true
          kubectl apply -f deployment.yaml

      - name: Expose Service URL
        run: |
          eval $(minikube docker-env)
          echo "Service URL:"
          minikube service hello-springboot-app-service --url || true

      - name: Verify Deployment & Pods
        run: |
          eval $(minikube docker-env)
          kubectl get deployments
          kubectl describe deployment hello-springboot-app
          kubectl get pods
          kubectl describe pod -l app=hello-springboot-app