name: Java Docker K8s Deployment

on:
  push:
    branches:
      - main  # Trigger only when code is pushed to 'main' branch
    paths:
      - 'Jenkins_Assignment_7/hello-springboot-app/**'  # Only trigger when files in this path change

jobs:
  build-and-deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Verify Minikube status
        run: minikube status

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven
        working-directory: Jenkins_Assignment_7/hello-springboot-app
        run: mvn clean package

      - name: Configure Docker to use Minikube
        run: eval $(minikube docker-env)

      - name: Build Docker image
        working-directory: Jenkins_Assignment_7/hello-springboot-app
        run: docker build -t hello-springboot-app:latest .

      - name: Verify Docker image exists
        run: docker images | grep hello-springboot-app

      - name: Deploy to Minikube
        working-directory: Jenkins_Assignment_7/hello-springboot-app
        run: |
          kubectl apply -f deployment.yaml
          kubectl get pods 
          echo "Service URL:"
          minikube service hello-springboot-app-service --url || true

      - name: Verify deployment
        run: |
          kubectl get deployments
          kubectl describe deployment hello-springboot-app
          kubectl get pods
          kubectl describe pod -l app=hello-springboot-app